function decoded = FSK_RRC_DecodeInfoWindow(rawSamples, captureSampleRateHz, sourceName, decodeArgs)
    % 后台信息波解码任务。
    %
    % 本函数只处理已经采集到的 IQ 窗口，不持有 Pluto。返回值仅保留自动
    % 比赛链路需要的小体积字段，避免把整段 IQ、鉴频结果和软比特流复制回
    % 采集线程。
    decodeStartTic = tic;
    decoded = struct( ...
        'ok', false, ...
        'errorText', "", ...
        'updates', local_empty_updates(), ...
        'validFrameCount', 0, ...
        'validPacketCount', 0, ...
        'evaluatedCandidateCount', 0, ...
        'metric', -inf, ...
        'decodeElapsedSec', 0);

    try
        recvArgs = [ ...
            {'SourceName', char(string(sourceName)), ...
             'InputSamples', rawSamples(:), ...
             'CaptureSampleRateHz', double(captureSampleRateHz), ...
             'EnablePlutoRx', false, ...
             'ReusePlutoRx', true, ...
             'SkipProjectSetup', true, ...
             'UseThreadSafeIntegerResample', false, ...
             'ShowPlots', false}, ...
            decodeArgs(:).'];
        consoleText = evalc('result = FSK_RRC_Recv(recvArgs{:});'); %#ok<NASGU>

        decoded.ok = true;
        decoded.updates = local_extract_updates(result);
        decoded.validFrameCount = double(result.best.validFrameCount);
        decoded.validPacketCount = double(result.best.validPacketCount);
        decoded.evaluatedCandidateCount = double(result.best.evaluatedCandidateCount);
        decoded.metric = double(result.best.metric);
    catch ME
        decoded.errorText = string(getReport(ME, 'extended', 'hyperlinks', 'off'));
    end
    decoded.decodeElapsedSec = toc(decodeStartTic);
end

function updates = local_extract_updates(result)
    updates = local_empty_updates();
    if ~isfield(result, 'best') || ~isfield(result.best, 'frames') || ...
            isempty(result.best.frames)
        return;
    end

    frames = result.best.frames;
    cmdIds = uint16([hex2dec('0A01'), hex2dec('0A02'), hex2dec('0A03'), ...
        hex2dec('0A04'), hex2dec('0A05')]);
    lengths = [24 12 10 8 41];
    for frameIdx = 1:numel(frames)
        frameResult = frames(frameIdx).result;
        if ~isfield(frameResult, 'ok') || ~frameResult.ok || ...
                ~isfield(frameResult, 'cmdId') || ~isfield(frameResult, 'dataBytes')
            continue;
        end
        cmdIndex = find(uint16(frameResult.cmdId) == cmdIds, 1);
        if isempty(cmdIndex) || numel(frameResult.dataBytes) < lengths(cmdIndex)
            continue;
        end
        updates(end+1) = struct( ... %#ok<AGROW>
            'cmdId', uint16(frameResult.cmdId), ...
            'index', double(cmdIndex), ...
            'seq', uint8(frameResult.seq), ...
            'dataBytes', uint8(frameResult.dataBytes(1:lengths(cmdIndex))), ...
            'type', string(frameResult.type));
    end
end

function updates = local_empty_updates()
    updates = struct( ...
        'cmdId', {}, 'index', {}, 'seq', {}, 'dataBytes', {}, 'type', {});
end
