function cfg = FSK_RRC_ProjectConfig()
    rootDir = fileparts(mfilename('fullpath'));

    cfg = struct();
    cfg.paths = struct('rootDir', rootDir);

    cfg.sources = struct( ...
        'redBroadcast', "red_broadcast", ...
        'redL1Jammer', "red_l1_jammer", ...
        'redL2Jammer', "red_l2_jammer", ...
        'redL3Jammer', "red_l3_jammer", ...
        'blueBroadcast', "blue_broadcast", ...
        'blueL1Jammer', "blue_l1_jammer", ...
        'blueL2Jammer', "blue_l2_jammer", ...
        'blueL3Jammer', "blue_l3_jammer", ...
        'broadcastList', ["red_broadcast", "blue_broadcast"], ...
        'jammerList', ["red_l1_jammer", "red_l2_jammer", "red_l3_jammer", "blue_l1_jammer", "blue_l2_jammer", "blue_l3_jammer"], ...
        'all', ["red_broadcast", "red_l1_jammer", "red_l2_jammer", "red_l3_jammer", "blue_broadcast", "blue_l1_jammer", "blue_l2_jammer", "blue_l3_jammer"]);

    cfg.sim = struct( ...
        'SourceName', "red_broadcast", ...
        'EbN0dB_vec', 0:1:25, ...
        'ShowPlots', true, ...
        'UseMultipath', false, ...
        'H_chan', [1 0 0.25*exp(1j*0.7)], ...
        'UseFlatFade', false, ...
        'RepeatInBuffer', 40);

    cfg.tx = struct( ...
        'SourceName', "red_l1_jammer", ...
        'RadioID', "ip:192.168.2.1", ...
        'TxGain_dB', 0, ...
        'TxTimeSec', inf, ...
        'RepeatInBuffer', 40, ...
        'EnablePlutoTx', true, ...
        'ShowPlots', true);

    cfg.rx = struct( ...
        'SourceName', "red_broadcast", ...
        'RxRadioID', "ip:192.168.2.1", ...
        'UseAGC', true, ...
        'AGCMode', "fast", ...                  % 实测邻道强信号下 Fast Attack 削顶更少、增益更稳定
        'RxGain_dB', 20, ...
        'CaptureSampleRateHz', 2.0e6, ...
        'InfoCaptureSampleRateHz', 1.0e6, ... % 信息波实测无 overflow，干扰波仍使用 2 MHz
        'RxCenterFrequencyOffsetHz', 0, ...      % 正值：硬件本振上移，解调前由数字 NCO 搬回
        'RxRFBandwidthHz', 0, ...              % 0/empty：严格使用当前波源的 rxBandwidth
        'SamplesPerFrame', 50000, ...
        'WarmupFrames', 4, ...
        'CaptureTimeSec', 0.8, ...
        'EnablePlutoRx', true, ...
        'InputSamples', [], ...
        'ShowPlots', true);
end
