function c = get_protocol_constants()
    c = struct( ...
        'otaPayloadLengthBytes', 15, ...
        'otaHeaderLengthBytes', 4, ...
        'otaPacketLengthBytes', 27, ...
        'otaHeaderBytes', uint8([0 15 0 15]).', ...
        'otaAccessCodeLengthBytes', 8, ...
        'protocolSofByte', uint8(hex2dec('A5')), ...
        'protocolHeaderLengthBytes', 5, ...
        'protocolCmdLengthBytes', 2, ...
        'protocolTailLengthBytes', 2, ...
        'protocolMinFrameLengthBytes', 9, ...
        'protocolCrc8Init', uint8(hex2dec('FF')), ...
        'protocolCrc16Init', uint16(hex2dec('FFFF')), ...
        'protocolCrc16Endian', "little", ...
        'infoAccessCodeHex', "2F6F4C74B914492E", ...
        'jammerAccessCodeHex', "16E8D377151C712D", ...
        'businessFieldEndian', "little", ...
        'validCmdIds', uint16(hex2dec({'0A01','0A02','0A03','0A04','0A05','0A06'})));

    c.infoAccessCodeBytes = local_hex_to_uint8(c.infoAccessCodeHex);
    c.jammerAccessCodeBytes = local_hex_to_uint8(c.jammerAccessCodeHex);
end

function bytes = local_hex_to_uint8(hexText)
    hexText = char(string(hexText));
    bytes = uint8(sscanf(hexText, '%2x').');
    bytes = bytes(:);
end
