function result = parse_protocol_frame(frameBytes)
    c = get_protocol_constants();
    frameBytes = uint8(frameBytes(:));

    result = struct( ...
        "ok", false, ...
        "complete", false, ...
        "sofOk", false, ...
        "crc8Ok", false, ...
        "crc16Ok", false, ...
        "cmdKnown", false, ...
        "type", "unknown", ...
        "seq", uint8(0), ...
        "dataLength", uint16(0), ...
        "cmdId", uint16(0), ...
        "dataBytes", uint8([]), ...
        "asciiText", "", ...
        "payload", struct(), ...
        "summary", "", ...
        "totalLength", uint16(0), ...
        "rawHex", "", ...
        "errorCode", "", ...
        "warningCode", "");

    result.rawHex = string(upper(reshape(dec2hex(frameBytes).', 1, [])));
    if numel(frameBytes) < c.protocolMinFrameLengthBytes
        result.errorCode = "short_frame";
        return;
    end

    result.sofOk = frameBytes(1) == c.protocolSofByte;
    result.dataLength = local_read_uint16(frameBytes(2:3), c.businessFieldEndian);
    result.seq = frameBytes(4);
    result.crc8Ok = crc8_calc(frameBytes(1:4), c.protocolCrc8Init) == frameBytes(5);
    result.cmdId = local_read_uint16(frameBytes(6:7), c.businessFieldEndian);
    result.cmdKnown = any(result.cmdId == c.validCmdIds);

    expectedLen = c.protocolHeaderLengthBytes + c.protocolCmdLengthBytes + double(result.dataLength) + c.protocolTailLengthBytes;
    result.totalLength = uint16(expectedLen);
    if numel(frameBytes) < expectedLen
        result.errorCode = "truncated_frame";
        return;
    end

    result.complete = true;
    frameBytes = frameBytes(1:expectedLen);
    crc16Actual = crc16_calc(frameBytes(1:end-2));
    crc16Expected = local_read_uint16(frameBytes(end-1:end), c.protocolCrc16Endian);
    result.crc16Ok = crc16Actual == crc16Expected;

    dataBytes = frameBytes(8:end-2);
    result.dataBytes = dataBytes(:);
    result.ok = result.sofOk && result.crc8Ok && result.crc16Ok;
    if ~result.ok
        result.errorCode = "crc_or_sof_error";
        return;
    end

    switch result.cmdId
        case uint16(hex2dec('0A01'))
            result.type = "broadcast_positions";
            if numel(dataBytes) >= 24
                vals = local_read_uint16_array(dataBytes(1:24), c.businessFieldEndian);
                result.payload = struct( ...
                    'heroX', vals(1), 'heroY', vals(2), ...
                    'engineerX', vals(3), 'engineerY', vals(4), ...
                    'infantry3X', vals(5), 'infantry3Y', vals(6), ...
                    'infantry4X', vals(7), 'infantry4Y', vals(8), ...
                    'aerialX', vals(9), 'aerialY', vals(10), ...
                    'sentryX', vals(11), 'sentryY', vals(12));
            else
                result.warningCode = "payload_too_short";
            end
        case uint16(hex2dec('0A02'))
            result.type = "broadcast_hp";
            if numel(dataBytes) >= 12
                vals = local_read_uint16_array(dataBytes(1:12), c.businessFieldEndian);
                result.payload = struct( ...
                    'heroHp', vals(1), ...
                    'engineerHp', vals(2), ...
                    'infantry3Hp', vals(3), ...
                    'infantry4Hp', vals(4), ...
                    'reserved', vals(5), ...
                    'sentryHp', vals(6));
            else
                result.warningCode = "payload_too_short";
            end
        case uint16(hex2dec('0A03'))
            result.type = "broadcast_projectiles";
            if numel(dataBytes) >= 10
                vals = local_read_uint16_array(dataBytes(1:10), c.businessFieldEndian);
                result.payload = struct( ...
                    'heroAmmo', vals(1), ...
                    'infantry3Ammo', vals(2), ...
                    'infantry4Ammo', vals(3), ...
                    'aerialAmmo', vals(4), ...
                    'sentryAmmo', vals(5));
            else
                result.warningCode = "payload_too_short";
            end
        case uint16(hex2dec('0A04'))
            result.type = "broadcast_economy";
            if numel(dataBytes) >= 8
                remainCoins = local_read_uint16(dataBytes(1:2), c.businessFieldEndian);
                totalCoins = local_read_uint16(dataBytes(3:4), c.businessFieldEndian);
                buffStatusBits = local_read_uint32(dataBytes(5:8), c.businessFieldEndian);
                result.payload = struct( ...
                    'remainCoins', remainCoins, ...
                    'totalCoins', totalCoins, ...
                    'buffStatusBits', buffStatusBits);
            else
                result.warningCode = "payload_too_short";
            end
        case uint16(hex2dec('0A05'))
            result.type = "broadcast_buffs";
            if numel(dataBytes) >= 41
                result.payload = local_parse_0A05_payload(dataBytes, c.businessFieldEndian);
            else
                result.warningCode = "payload_too_short";
            end
        case uint16(hex2dec('0A06'))
            result.type = "jammer_key";
            result.asciiText = string(char(dataBytes(:).'));
            result.payload = struct( ...
                'jammerKey', result.asciiText, ...
                'isValidAlphaNum', local_is_valid_jammer_key(dataBytes));
            if numel(dataBytes) ~= 6
                result.warningCode = "invalid_jammer_key_length";
            elseif ~result.payload.isValidAlphaNum
                result.warningCode = "invalid_jammer_key_charset";
            end
        otherwise
            result.type = "unknown_command";
            result.warningCode = "unknown_command";
    end

    result.summary = protocol_frame_to_text(result);
end

function payload = local_parse_0A05_payload(dataBytes, endianMode)
    payload = struct( ...
        'heroRegen', dataBytes(1), ...
        'heroCooling', local_read_uint16(dataBytes(2:3), endianMode), ...
        'heroDefense', dataBytes(4), ...
        'heroNegDefense', dataBytes(5), ...
        'heroAttack', local_read_uint16(dataBytes(6:7), endianMode), ...
        'engineerRegen', dataBytes(8), ...
        'engineerCooling', local_read_uint16(dataBytes(9:10), endianMode), ...
        'engineerDefense', dataBytes(11), ...
        'engineerNegDefense', dataBytes(12), ...
        'engineerAttack', local_read_uint16(dataBytes(13:14), endianMode), ...
        'infantry3Regen', dataBytes(15), ...
        'infantry3Cooling', local_read_uint16(dataBytes(16:17), endianMode), ...
        'infantry3Defense', dataBytes(18), ...
        'infantry3NegDefense', dataBytes(19), ...
        'infantry3Attack', local_read_uint16(dataBytes(20:21), endianMode), ...
        'infantry4Regen', dataBytes(22), ...
        'infantry4Cooling', local_read_uint16(dataBytes(23:24), endianMode), ...
        'infantry4Defense', dataBytes(25), ...
        'infantry4NegDefense', dataBytes(26), ...
        'infantry4Attack', local_read_uint16(dataBytes(27:28), endianMode), ...
        'sentryRegen', dataBytes(29), ...
        'sentryCooling', local_read_uint16(dataBytes(30:31), endianMode), ...
        'sentryDefense', dataBytes(32), ...
        'sentryNegDefense', dataBytes(33), ...
        'sentryAttack', local_read_uint16(dataBytes(34:35), endianMode), ...
        'sentryPose', dataBytes(36), ...
        'heroMainStatus', dataBytes(37), ...
        'engineerMainStatus', dataBytes(38), ...
        'infantry3MainStatus', dataBytes(39), ...
        'infantry4MainStatus', dataBytes(40), ...
        'sentryMainStatus', dataBytes(41));
end

function value = local_read_uint16(bytes, endianMode)
    bytes = uint8(bytes(:));
    if string(endianMode) == "big"
        bytes = flipud(bytes);
    end
    value = typecast(bytes, 'uint16');
end

function values = local_read_uint16_array(bytes, endianMode)
    bytes = uint8(bytes(:));
    n = floor(numel(bytes)/2);
    values = zeros(n, 1, 'uint16');
    for k = 1:n
        idx = 2*k - 1;
        values(k) = local_read_uint16(bytes(idx:idx+1), endianMode);
    end
end

function value = local_read_uint32(bytes, endianMode)
    bytes = uint8(bytes(:));
    if string(endianMode) == "big"
        bytes = flipud(bytes);
    end
    value = typecast(bytes, 'uint32');
end

function tf = local_is_valid_jammer_key(dataBytes)
    chars = char(uint8(dataBytes(:)).');
    tf = numel(chars) == 6 && all(isstrprop(chars, 'alphanum'));
end
