function rxReference = build_gfsk_rx_reference(sourceName)
    cfg = get_gfsk_source_config(sourceName);
    c = get_protocol_constants();

    h_gauss = make_gaussian_taps(cfg.bt, cfg.gaussianSpan, cfg.sps);
    samplePhaseGroupDelay = (numel(h_gauss) - 1) / 2;
    demodLpfHz = min(4 * cfg.Rs, 0.45 * cfg.Fs);

    otaPacketCountPerCycle = cfg.payloadBytesPerCycle / c.otaPayloadLengthBytes;
    packetDurationSec = c.otaPacketLengthBytes * 8 / cfg.bitRate;
    cycleDurationSec = 1 / cfg.cycleRateHz;

    if cfg.waveType == "broadcast"
        protocolFrameCountPerCycle = 5;
    else
        protocolFrameCountPerCycle = 1;
    end

    rxReference = struct( ...
        'Fs', cfg.Fs, ...
        'Rs', cfg.Rs, ...
        'sps', cfg.sps, ...
        'rfBandwidth', cfg.rfBandwidth, ...
        'sensitivity', cfg.sensitivity, ...
        'dataPushRateBytesPerSec', cfg.dataPushRateBytesPerSec, ...
        'payloadBytesPerCycle', cfg.payloadBytesPerCycle, ...
        'cycleRateHz', cfg.cycleRateHz, ...
        'accessCodeBytes', cfg.accessCodeBytes(:), ...
        'sourceName', cfg.name, ...
        'samplePhaseGroupDelay', samplePhaseGroupDelay, ...
        'demodLpfHz', demodLpfHz, ...
        'cycleDurationSec', cycleDurationSec, ...
        'protocolFrameCountPerCycle', protocolFrameCountPerCycle, ...
        'otaPacketCountPerCycle', otaPacketCountPerCycle);
end
