function txData = build_gfsk_tx_waveform(sourceName, repeatInBuffer, jammerKey)
    if nargin < 1 || strlength(string(sourceName)) == 0
        sourceName = "blue_broadcast";
    end
    if nargin < 2 || isempty(repeatInBuffer)
        repeatInBuffer = 40;
    end
    if nargin < 3
        jammerKey = "";
    end

    cfg = get_gfsk_source_config(sourceName);
    cfg.repeatInBuffer = repeatInBuffer;
    cfgRule = validate_gfsk_source_config(cfg);

    cycleSpec = get_source_protocol_cycle(cfg, jammerKey);
    % 140 字节信息周期不能被 15 字节 OTA Payload 整除。先拼完整个有限
    % 发射缓存，再仅在缓存尾部补齐最后一包，保证周期边界连续切片。
    % 每个业务周期递增协议头 seq；即使五类业务数值没有变化，接收端也能
    % 区分“官方新一轮”与重叠窗口对同一物理帧的重复确认。
    protocolPayloadBytes = zeros( ...
        cfg.repeatInBuffer * cfg.payloadBytesPerCycle, 1, 'uint8');
    protocolWrite = 1;
    frameCountPerCycle = numel(cycleSpec.protocolFrames);
    for cycleIdx = 0:cfg.repeatInBuffer-1
        sequenceBase = uint8(mod(cycleIdx * frameCountPerCycle, 256));
        currentCycle = get_source_protocol_cycle(cfg, jammerKey, sequenceBase);
        cycleBytes = currentCycle.protocolStreamBytes(:);
        protocolPayloadBytes( ...
            protocolWrite:protocolWrite + numel(cycleBytes) - 1) = cycleBytes;
        protocolWrite = protocolWrite + numel(cycleBytes);
    end
    bufferOtaSpec = build_ota_stream(protocolPayloadBytes, cfg.accessCodeBytes);
    bits = bufferOtaSpec.streamBits(:);
    bitLevels = 2 * double(bits) - 1;

    h_gauss = make_gaussian_taps(cfg.bt, cfg.gaussianSpan, cfg.sps);
    bitWave = repelem(bitLevels, cfg.sps);
    shapedControl = filter(h_gauss, 1, bitWave);

    phaseStep = cfg.sensitivity * shapedControl;
    phi = cumsum(phaseStep);
    s_bb_burst = exp(1j * phi);

    % 数据到达即发射，但平均推送速率仍由 cycleRateHz/dataPushRate 控制。
    % OTA 突发结束后补无射频输出的零样本，使整个缓存覆盖整数个业务周期。
    targetBufferSamples = round(cfg.repeatInBuffer / cfg.cycleRateHz * cfg.Fs);
    if numel(s_bb_burst) > targetBufferSamples
        error(['当前 GFSK/OTA 参数无法在目标推送速率内发送：需要 %d 样本，' ...
            '业务周期只提供 %d 样本。'], numel(s_bb_burst), targetBufferSamples);
    end
    idleSampleCount = targetBufferSamples - numel(s_bb_burst);
    s_bb = [s_bb_burst; complex(zeros(idleSampleCount, 1))];
    s_tx = 0.8 * s_bb;

    demodLpfHz = min(4 * cfg.Rs, 0.45 * cfg.Fs);

    txData = struct( ...
        "cfg", cfg, ...
        "cfgRule", cfgRule, ...
        "cycleSpec", cycleSpec, ...
        "protocolFrames", cycleSpec.protocolFrames, ...
        "payloadInfo", cycleSpec.protocolFrames, ...
        "otaBytesOneCycle", cycleSpec.otaSpec.streamBytes(:), ...
        "otaBitsOneCycle", cycleSpec.otaSpec.streamBits(:), ...
        "bufferOtaSpec", bufferOtaSpec, ...
        "otaPacketCountInBuffer", bufferOtaSpec.numPackets, ...
        "protocolFrameCountInBuffer", cfg.repeatInBuffer * cycleSpec.protocolFrameCountPerCycle, ...
        "idleSampleCount", idleSampleCount, ...
        "protocolStreamBytesOneCycle", cycleSpec.protocolStreamBytes(:), ...
        "protocolStreamBitsOneCycle", cycleSpec.protocolStreamBits(:), ...
        "bits", bits(:), ...
        "bitLevels", bitLevels(:), ...
        "bitWave", bitWave(:), ...
        "h_gauss", h_gauss(:), ...
        "shapedControl", shapedControl(:), ...
        "phaseStep", phaseStep(:), ...
        "phi", phi(:), ...
        "s_bb", s_bb(:), ...
        "s_tx", s_tx(:), ...
        "samplePhaseGroupDelay", (numel(h_gauss) - 1) / 2, ...
        "demodLpfHz", demodLpfHz, ...
        "rxReference", local_build_rx_reference(cfg, h_gauss, demodLpfHz));
end

function rxReference = local_build_rx_reference(cfg, h_gauss, demodLpfHz)
    rxReference = struct( ...
        'Fs', cfg.Fs, ...
        'Rs', cfg.Rs, ...
        'sps', cfg.sps, ...
        'rfBandwidth', cfg.rfBandwidth, ...
        'sensitivity', cfg.sensitivity, ...
        'dataPushRateBytesPerSec', cfg.dataPushRateBytesPerSec, ...
        'payloadBytesPerCycle', cfg.payloadBytesPerCycle, ...
        'cycleRateHz', cfg.cycleRateHz, ...
        'accessCodeBytes', cfg.accessCodeBytes(:), ...
        'sourceName', cfg.name, ...
        'samplePhaseGroupDelay', (numel(h_gauss) - 1) / 2, ...
        'demodLpfHz', demodLpfHz);
end
