function cfg = get_gfsk_source_config(sourceName)
    sourceName = string(sourceName);
    common = local_get_common_profile_config();

    % rxBandwidth 是写入 Pluto 的实际接收带宽，按原严格带宽放大到 1.25 倍留余量。
    profiles = [
        local_profile("red_broadcast",  "红方广播源",   "broadcast", "blue", 433.20e6, 0.54e6, 0.6875e6, -60, common)
        local_profile("red_l1_jammer",  "红方一级干扰源", "jammer", "blue", 432.20e6, 0.94e6, 1.1750e6, -10, common)
        local_profile("red_l2_jammer",  "红方二级干扰源", "jammer", "blue", 432.50e6, 0.86e6, 1.0750e6, -10, common)
        local_profile("red_l3_jammer",  "红方三级干扰源", "jammer", "blue", 432.80e6, 0.25e6, 0.3125e6, -10, common)
        local_profile("blue_broadcast", "蓝方广播源",   "broadcast", "red",  433.92e6, 0.54e6, 0.6875e6, -60, common)
        local_profile("blue_l1_jammer", "蓝方一级干扰源", "jammer", "red",  434.92e6, 0.94e6, 1.1750e6, -10, common)
        local_profile("blue_l2_jammer", "蓝方二级干扰源", "jammer", "red",  434.62e6, 0.86e6, 1.0750e6, -10, common)
        local_profile("blue_l3_jammer", "蓝方三级干扰源", "jammer", "red",  434.32e6, 0.25e6, 0.3125e6, -10, common)
    ];

    names = [profiles.name];
    idx = find(strcmp(names, sourceName), 1);
    if isempty(idx)
        error("未知 sourceName: '%s'.", sourceName);
    end

    cfg = profiles(idx);
end

function common = local_get_common_profile_config()
    c = get_protocol_constants();
    common = struct( ...
        'Fs', 1e6, ...
        'sps', 47, ...
        'bt', 0.35, ...
        'gaussianSpan', 4, ...
        'otaPayloadLengthBytes', c.otaPayloadLengthBytes, ...
        'otaHeaderLengthBytes', c.otaHeaderLengthBytes, ...
        'otaPacketLengthBytes', c.otaPacketLengthBytes, ...
        'cycleRateHz', 10, ...
        'infoDataPushRateBytesPerSec', 1400, ...
        'jammerDataPushRateBytesPerSec', 1350, ...
        'repeatInBuffer', 40, ...
        'infoAccessCodeHex', c.infoAccessCodeHex, ...
        'infoAccessCodeBytes', c.infoAccessCodeBytes, ...
        'jammerAccessCodeHex', c.jammerAccessCodeHex, ...
        'jammerAccessCodeBytes', c.jammerAccessCodeBytes);
end

function cfg = local_profile(name, displayName, waveType, opponentColor, fc, rfBandwidth, rxBandwidth, power_dBm, common)
    Rs = common.Fs / common.sps;
    deltaF = rfBandwidth / 2 - Rs;
    sensitivity = 2*pi*deltaF/common.Fs;

    if waveType == "broadcast"
        accessCodeHex = common.infoAccessCodeHex;
        accessCodeBytes = common.infoAccessCodeBytes;
        dataPushRateBytesPerSec = common.infoDataPushRateBytesPerSec;
    else
        accessCodeHex = common.jammerAccessCodeHex;
        accessCodeBytes = common.jammerAccessCodeBytes;
        dataPushRateBytesPerSec = common.jammerDataPushRateBytesPerSec;
    end
    payloadBytesPerCycle = dataPushRateBytesPerSec / common.cycleRateHz;

    cfg = struct( ...
        "name", name, ...
        "displayName", displayName, ...
        "waveType", waveType, ...
        "opponentColor", opponentColor, ...
        "fc", fc, ...
        "rfBandwidth", rfBandwidth, ...
        "rxBandwidth", rxBandwidth, ...
        "power_dBm", power_dBm, ...
        "Fs", common.Fs, ...
        "Rs", Rs, ...
        "bitRate", Rs, ...
        "sps", common.sps, ...
        "bt", common.bt, ...
        "gaussianSpan", common.gaussianSpan, ...
        "deltaF", deltaF, ...
        "sensitivity", sensitivity, ...
        "accessCodeHex", accessCodeHex, ...
        "accessCodeBytes", accessCodeBytes(:), ...
        "otaPayloadLengthBytes", common.otaPayloadLengthBytes, ...
        "otaHeaderLengthBytes", common.otaHeaderLengthBytes, ...
        "otaPacketLengthBytes", common.otaPacketLengthBytes, ...
        "payloadBytesPerCycle", payloadBytesPerCycle, ...
        "cycleRateHz", common.cycleRateHz, ...
        "dataPushRateBytesPerSec", dataPushRateBytesPerSec, ...
        "repeatInBuffer", common.repeatInBuffer);
end
