function summary = validate_gfsk_source_config(cfg)
    tol = 1e-9;

    expectedSps = cfg.Fs / cfg.Rs;
    expectedSensitivity = 2*pi*(cfg.rfBandwidth/2 - cfg.Rs) / cfg.Fs;
    payloadBytesPerCycle = cfg.dataPushRateBytesPerSec / cfg.cycleRateHz;

    summary = struct( ...
        "expectedSps", expectedSps, ...
        "spsOk", abs(cfg.sps - expectedSps) < tol, ...
        "btOk", abs(cfg.bt - 0.35) < tol, ...
        "fsOk", abs(cfg.Fs - 1e6) < tol, ...
        "sensitivityOk", abs(cfg.sensitivity - expectedSensitivity) < 1e-4, ...
        "payloadCycleOk", abs(cfg.payloadBytesPerCycle - payloadBytesPerCycle) < tol, ...
        "allOk", false);

    summary.allOk = summary.spsOk && summary.btOk && summary.fsOk && ...
        summary.sensitivityOk && summary.payloadCycleOk;

    if ~summary.allOk
        error("源配置 '%s' 不满足 2-GFSK 规则约束。", cfg.name);
    end
end

